booking/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.booking_view,
         name='booking'),
    path('manage-bookings/', views.AllBookings.as_view(),
         name='manage_bookings'),
    path('my-bookings/', views.UserBookings.as_view(),
         name='user_bookings'),
    path('my-bookings/edit/<str:id>', views.booking_edit,
         name='booking_edit'),
    path('my-bookings/delete/<str:id>', views.booking_delete,
         name='booking_delete'),
    path('manage-bookings/delete/<str:id>', views.booking_delete,
         name='booking_delete'),
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index_page, name='home'),
]

lakeview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('about/', include('about.urls'), name='about-urls'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls'), name='booking-urls'),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls'), name='home-urls'),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import date, timedelta
import uuid


class Booking(models.Model):
    """
    A model for campsite bookings.

    Fields:
        ACCOMMODATION (Tuple) - A set of options for accomodation type.
        booking_id (CharField) - A universally unique identifier for the
                                 booking.
        booked_by (ForeignKey) - The user who created the booking referenced
                                 from the Django User model.
        created_on (DateTimeField) - The date and time the booking was created.
        updated_on (DateTimeField) - The date and time the booking was last
                                     updated.
        accommodation (IntegerField) - The integer choice corresponding to the
                                       string in the ACCOMMODATION tuple.
        arrival (DateField) - The arrival date for the booking.
        departure (DateField) - The departure date for the booking.
        adults (PositiveIntegerField) - An integer number of adults in the
                                        booking with a minimum value of 1.
        children (PositiveIntegerField) - An integer number of children in the
                                          booking with a minimum value of 0.
        booked (BooleanField) - The booking status of the booking request:
                                True if user has accepted terms and
                                conditions, otherwise False.
    """

    ACCOMMODATION = ((0, 'Tent'), (1, 'Van'), (2, 'Caravan'), (3, 'Yurt'))

    booking_id = models.CharField(max_length=36, default=uuid.uuid4)
    booked_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bookings'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    accommodation = models.IntegerField(choices=ACCOMMODATION, default=0)
    arrival = models.DateField()
    departure = models.DateField()
    adults = models.PositiveIntegerField(default=1,
                                         validators=[
                                            MinValueValidator(1),
                                            MaxValueValidator(10)
                                            ])
    children = models.PositiveIntegerField(default=0,
                                           validators=[MaxValueValidator(10)])
    booked = models.BooleanField(default=False)

    class Meta:
        """
        Meta class for the booking form. Specifies how to sort the bookings
        in querysets.
        """

        ordering = ["arrival"]

    def __str__(self):
        """
        Method to return a string with relevant booking details.

        Returns the arrival date, accommodation type, name of the user who made
        the booking, and the unique booking ID.
        """

        return f'{self.arrival} | \
            {dict(self.ACCOMMODATION).get(self.accommodation)} booking by \
                {self.booked_by.first_name} {self.booked_by.last_name} | \
                    Booking id: {self.booking_id}'

    def string_from_tuple(self):
        """
        Method to return the string value of the accommodation type from the
        ACCOMMODATION tuple.
        """

        return f'{dict(self.ACCOMMODATION).get(self.accommodation)}'

    def is_in_past(self):
        """
        Method to return a boolean True if the departure date is in the past,
        and False if it is not.
        """

        return date.today() > self.departure

    def is_within_48h(self):
        """
        Method to return a boolean True is the arrival date is within the next
        48 hours, and false if it is not.
        """

        return self.arrival < date.today() + timedelta(hours=48)

    def full_name(self):
        """
        Method to return the full name of the user who made a given booking
        in the form of a string.
        """
        if self.booked_by.first_name:
            return f'{self.booked_by.first_name} {self.booked_by.last_name}'
        else:
            return False

booking/forms.py
from .models import Booking
from django import forms
from django.forms.widgets import DateInput, SelectDateWidget, NumberInput, \
    RadioSelect
from datetime import date, timedelta
from django.core.exceptions import ValidationError


class BookingForm(forms.ModelForm):
    """
    Form for making campsite bookings. The user can specify the type of
    booking, the arrival and departure dates, the number of adults and
    children in the booking, and whether they accept the terms and conditions.
    """

    class Meta:
        """
        Meta class for the form's metadata. Specifies the model to be used
        with the form and the fields to use. Widget attributes are also
        specified in this class.
        """

        model = Booking
        fields = (
            'accommodation',
            'arrival',
            'departure',
            'adults',
            'children',
            'booked',
        )
        labels = {
            'booked': 'I agree to the Terms and Conditions',
        }
        widgets = {
            'arrival': DateInput(attrs={
                'type': 'date',
                'id': 'arrival',
                'min': date.today() + timedelta(days=1)
                }),
            'departure': DateInput(attrs={
                'type': 'date',
                'id': 'departure',
                'min': date.today() + timedelta(days=2)
                }),
        }

    def clean(self):
        """
        Validation of form data on the back end.

        The method ensures that the departure date can neither be on the same
        date as the arrival nor can it be before the date of arrival.

        If the data validates, the method returns the cleaned data.
        If invalid, it raises a validation error to inform the user.
        """

        cleaned_data = super().clean()
        arrival = cleaned_data.get('arrival')
        departure = cleaned_data.get('departure')
        booked = cleaned_data.get('booked')

        if arrival > departure:
            raise ValidationError('Please select a departure date after your'
                                  ' arrival.')

        if arrival == departure:
            raise ValidationError('The minimum length of stay is one night.')

        if not booked:
            raise ValidationError('You must accept the Terms and Conditions'
                                  ' before booking.')

        return cleaned_data

booking/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from .forms import BookingForm
from .models import Booking
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied


class StaffCheck(UserPassesTestMixin, generic.ListView):
    def test_func(self):
        return self.request.user.is_staff


class UserBookings(LoginRequiredMixin, generic.ListView):
    """
    View that shows bookings made by users ordered by arrival date in
    descending order.
    The path for the template used to render the list is declared.
    """

    template_name = 'booking/user_bookings.html'

    def get_queryset(self):
        """
        Method to get a queryset of bookings.

        The queryset is filtered so that only bookings made by the currently
        authenticated user can be seen. The bookings are ordered by arrival
        date in descending order.
        """

        queryset = Booking.objects.all().order_by(
            '-arrival'
            ).filter(
                booked_by=self.request.user
                )
        return queryset


class AllBookings(StaffCheck, generic.ListView):
    """
    View that shows all bookings ordered by arrival date in descending order.
    The path for the template used to render the list is declared.
    """

    template_name = 'booking/manage_bookings.html'

    def get_queryset(self):
        """
        Method to get a queryset of bookings.

        The queryset is filtered so that all bookings are listed in order by
        arrival date in descending order.
        """

        queryset = Booking.objects.all().order_by('-arrival')
        return queryset


def booking_view(request):
    """
    Method to handle the booking form.

    Method processes the user-submitted data and checks if it is valid.
    If it is, the method saves the data and assigns the current user as the
    booking's creator.
    A message is shown on the front end to denote a successful booking.
    If the data is invalid, the form is re-rendered and shows appropriate
    error messages.
    """

    if request.method == 'POST':
        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():
            booking = booking_form.save(commit=False)
            booking.booked_by = request.user
            booking.save()
            messages.add_message(
                request, messages.SUCCESS, "Booking received! We will be in "
                "touch to facilitate payment and confirm your booking shortly."
                )
        else:
            booking_form = BookingForm(data=request.POST)
            return render(
                request,
                "booking/booking.html",
                {
                    "booking_form": booking_form,
                },
            )

    booking_form = BookingForm()

    return render(
        request,
        "booking/booking.html",
        {
            "booking_form": booking_form,
        },
    )


@login_required
def booking_edit(request, id):
    """
    Method to allow users to edit a booking.

    Takes in the booking id and fills the form with the relevant data for the
    user to edit.
    """

    booking = get_object_or_404(Booking, id=id)

    if booking.booked_by == request.user or request.user.is_staff:
        if request.method == 'GET':
            booking_form = BookingForm(instance=booking)
            return render(request, 'booking/booking.html',
                          {'booking_form': booking_form, 'id': id})
        elif request.method == 'POST':
            booking_form = BookingForm(request.POST, instance=booking)
            if booking_form.is_valid():
                booking_form.save()
                messages.add_message(
                    request, messages.SUCCESS, "Booking successfully updated!"
                )
                if request.user.is_staff:
                    return redirect('manage_bookings')
                else:
                    return redirect('user_bookings')
            else:
                booking_form = BookingForm(data=request.POST)
                return render(
                    request,
                    "booking/booking.html",
                    {
                        "booking_form": booking_form,
                    },
                )
                messages.add_message(
                    request, messages.SUCCESS, "Invalid form data."
                                               " Please check your inputs."
                )
        else:
            return HttpResponseBadRequest('Unsupported request method.')
    else:
        raise PermissionDenied


@login_required
def booking_delete(request, id):
    """
    Method to allow a user to delete their booking.

    Takes in the booking ID and verifies both the user's authorisation to
    delete the booking and if the booking can be deleted.
    """

    booking = get_object_or_404(Booking, id=id)

    if booking.booked_by == request.user or request.user.is_staff:
        if (booking.booked_by == request.user and
                not booking.is_within_48h()) or request.user.is_staff:
            booking.delete()
            messages.add_message(
                    request, messages.SUCCESS, "Booking successfully deleted!"
                    )
        else:
            messages.add_message(
                request, messages.ERROR, "It was not possible to delete this"
                " booking."
            )
        if request.user.is_staff:
            return redirect('manage_bookings')
        else:
            return redirect('user_bookings')
    else:
        raise PermissionDenied

booking/templates/booking/manage_bookings.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid mb-3">

    <!-- Hero Image -->
    <div class="row d-md-none d-lg-none d-xl-none">
        <div class="col-12 g-0">
            <img class="img-fluid" src="{% static 'images/tent-book-sm.webp' %}" alt="A coffee cup, camera, and book on the floor of a tent.">
        </div>
    </div>
    <div class="row d-none d-md-block d-lg-block d-xl-block d-xxl-block">
        <div class="col-12 g-0">
            <img class="img-fluid w-100" src="{% static 'images/wide-tent-lake.webp' %}" alt="A tent and chair in front of a lake.">
        </div>
    </div>

    <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
                                    fade show mt-3" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Manage Bookings Section -->
    <div class="row mt-3">
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <h1 class="sedan-regular">Manage Bookings</h1>
            {% if user.is_authenticated %}
            <p>You are logged in as: {{ user }}</p>
            {% endif %}
        </div>
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <h2 class="sedan-regular">Upcoming Bookings</h2>
        </div>
        <!-- Upcoming Bookings List -->
        {% for booking in booking_list %}
        {% if not booking.is_in_past %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="card mt-1 mb-1 text-center">
                {% if booking.full_name %}
                <h3 class='fs-5 sedan-regular mt-2'>{{ booking.full_name }}</h3>
                {% else %}
                <h3 class='fs-5 sedan-regular mt-2'>{{ booking.booked_by }}</h3>
                {% endif %}
                <p class="m-1">{{ booking.string_from_tuple }} Booking</p>
                <p class="m-1">{{ booking.arrival }} - {{ booking.departure }} </p>
                <p class="m-1">Adults: {{ booking.adults }}
                {% if booking.children %}
                - Children: {{ booking.children }} </p>
                {% else %}
                </p>
                {% endif %}
                <div class="row m-3">
                    <div class="col-6">
                        <a class="btn btn-outline-dark" href="{% url 'booking_edit' booking.id %}">
                            Manage
                        </a>
                    </div>
                    <div class="col-6">
                        <button type="button" class="btn btn-outline-danger btn-delete" data-bs-toggle="modal"
                            data-bs-target="#deleteModal" data-booking_id="{{ booking.id }}">
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% empty %}
        <p>There are no upcoming bookings.</p>
        {% endfor %}

        <!-- Past Bookings List -->
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <h2 class="sedan-regular mt-3 mb-1">Past Bookings</h2>
        </div>
        {% for booking in booking_list %}
        {% if booking.is_in_past %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="card mt-1 mb-1 text-center bg-secondary-subtle">
                {% if booking.full_name %}
                <h3 class='fs-5 sedan-regular mt-2'>{{ booking.full_name }}</h3>
                {% else %}
                <h3 class='fs-5 sedan-regular mt-2'>{{ booking.booked_by }}</h3>
                {% endif %}
                <p class="m-1">{{ booking.string_from_tuple }} Booking</p>
                <p class="m-1">{{ booking.arrival }} - {{ booking.departure }} </p>
                <p class="m-1">Adults: {{ booking.adults }}
                    {% if booking.children %}
                    - Children: {{ booking.children }} </p>
                {% else %}
                </p>
                {% endif %}
            </div>
        </div>
        {% endif %}
        {% empty %}
        <p>There are no past bookings.</p>
        {% endfor %}
    </div>
</div>

<!-- Modals -->
<!-- Confirming User Delete Action -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="deleteModalLabel">Delete booking?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    Are you sure you want to delete this booking?
                    This action cannot be undone.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Cancel
                </button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">
                    Delete
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Javascript Link -->
<script src="{% static 'js/user_bookings.js' %}"></script>
{% endblock content %}

booking/templates/booking/user_bookings.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid mb-3">

    <!-- Hero Image -->
    <div class="row d-md-none d-lg-none d-xl-none">
        <div class="col-12 g-0">
            <img class="img-fluid" src="{% static 'images/lake-chair-tent.webp' %}"
                alt="A tent and chair by the side of a lake.">
        </div>
    </div>
    <div class="row d-none d-md-block d-lg-block d-xl-block d-xxl-block">
        <div class="col-12 g-0">
            <img class="img-fluid w-100" src="{% static 'images/wide-tent-lake.webp' %}"
                alt="A tent and chair in front of a lake.">
        </div>
    </div>

    <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show mt-3" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- User Bookings Section -->
    <div class="row mt-3">
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <h1 class="sedan-regular">My Bookings</h1>
            {% if user.is_authenticated %}
            <p>You are logged in as: {{ user }}</p>
            {% endif %}
        </div>
        <!-- Upcoming Bookings List -->
        {% for booking in booking_list %}
        {% if not booking.is_in_past %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="card mt-1 mb-1 text-center">
                <h2 class='fs-5 sedan-regular m-1'>{{ booking.string_from_tuple }} Booking</h2>
                <p class="m-1">{{ booking.arrival }} </p>
                <p>
                    <a data-bs-toggle="collapse" href="#collapse{{ booking.booking_id }}" role="button"
                        aria-expanded="false" aria-controls="collapse{{ booking.booking_id }}"
                        class="details">
                        More Details
                    </a>
                </p>
                <div class="collapse" id="collapse{{ booking.booking_id }}">
                    <div class="card card-body">
                        <p class="m-1">Arrival: {{ booking.arrival }} </p>
                        <p class="m-1">Departure: {{ booking.departure }} </p>
                        <p class="m-1">Adults: {{ booking.adults }} </p>
                        {% if booking.children %}
                        <p class="m-1">Children: {{ booking.children }} </p>
                        {% endif %}
                        {% if not booking.is_within_48h %}
                        <div class="row mt-2">
                            <div class="col-6">
                                <a class="btn btn-outline-dark" href="{% url 'booking_edit' booking.id %}">
                                    Edit
                                </a>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn btn-outline-danger btn-delete" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal" data-booking_id="{{ booking.id }}">
                                    Delete
                                </button>
                            </div>
                        </div>
                        {% else %}
                        <!-- Button trigger modal -->
                        <!-- Code adapted from Bootstrap Documentation -->
                        <div class="row mt-2">
                            <div class="col-6">
                                <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal"
                                    data-bs-target="#within48hModal">
                                    Edit
                                </button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
                                    data-bs-target="#within48hModal">
                                    Delete
                                </button>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% empty %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <p>You have no upcoming bookings.</p>
        </div>
        {% endfor %}

        <!-- Past Bookings List -->
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <h1 class="sedan-regular mt-3 mb-1">Past Bookings</h1>
        </div>
        {% for booking in booking_list %}
        {% if booking.is_in_past %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="card mt-1 mb-1 text-center bg-secondary-subtle">
                <h2 class='fs-5 sedan-regular m-1'>{{ booking.string_from_tuple }} Booking</h2>
                <p class="m-1">{{ booking.arrival }} </p>
                <p>
                    <a data-bs-toggle="collapse" href="#collapse{{ booking.booking_id }}" role="button"
                        aria-expanded="false" aria-controls="collapse{{ booking.booking_id }}"
                        class="details">
                        More Details
                    </a>
                </p>
                <div class="collapse" id="collapse{{ booking.booking_id }}">
                    <div class="card card-body bg-secondary-subtle">
                        <p class="m-1">Arrived: {{ booking.arrival }} </p>
                        <p class="m-1">Departed: {{ booking.departure }} </p>
                        <p class="m-1">Adults: {{ booking.adults }} </p>
                        {% if booking.children %}
                        <p class="m-1">Children: {{ booking.children }} </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% empty %}
        <div class="col-10 offset-1 col-sm-6 offset-sm-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <p>You have no past bookings.</p>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Modals -->
<!-- Amending a booking within 48 hours (Code taken from Bootstrap Documentation)  -->
<div class="modal fade" id="within48hModal" tabindex="-1" aria-labelledby="within48hModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title fs-5" id="within48hModalLabel">It is not possible to amend your booking.
                </h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Your arrival date is within the next 48 hours. Please contact us directly to discuss your booking.
                </p>
                <p>Phone: <a href="tel:555-1234567"
                        aria-label="Call us (opens your phone app or program and auto-fills our phone number)">(555)
                        123-4567</a></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Understood</button>
            </div>
        </div>
    </div>
</div>
<!-- Confirming User Delete Action -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="deleteModalLabel">Delete booking?</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    Are you sure you want to delete your booking?
                    This action cannot be undone.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Cancel
                </button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">
                    Delete
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Javascript Link -->
<script src="{% static 'js/user_bookings.js' %}"></script>
{% endblock content %}